### ISSUE TITLE
Found an infinite. You need to get this patched FAST

### ISSUE THREAD

**Issue by HaxTheCharizard** [JoshTClark/Thalassophobia#1]
My guess is this is just caused by having both the Overclocked Control Unit and Chimeric Mask while in the Bazaar. As soon as I got kicked out for attacking Newt, THIS happened.
![purgatory](https://user-images.githubusercontent.com/68970651/213031230-76e32442-78fb-4afc-accd-37685dc12050.png)

**Comment by JoshTClark** [comment]
Yea any of the summoning items are pretty glitchy right now. I'll look into that as soon as I find some time. Need to un-spaghetti the code.

**Comment by JoshTClark** [comment]
The issue should be fixed. I cleaned up the wisp summon code in general so there shouldn't be any other weird issues. The OCU can now no longer inherit the wisp summoning items which I believe was the issue here.
