### ISSUE TITLE
Spawn rate for nullifying elites is EXTREMELY high

### ISSUE THREAD

**Issue by Sozzer-0** [JoshTClark/Thalassophobia#2]
Title. Playing with my partner and pretty much every third or fourth enemy was a nullifier from the first second. Rolled back to 1.1, sure enough, they're gone.

Could be an interaction with another mod, this is just a heads up to check if it's the case on your end too. Using artifact of swarms, which also could affect it somehow.

Let me know if you can't reproduce it, I'll grab a modlist.

**Comment by JoshTClark** [comment]
Should be adjusted now
